name: Cypress

on: [push]

jobs:
  cypress-run:
    name: Run Cypress Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run cypress
        uses: cypress-io/github-action@v2
        with:
          start: yarn web
          wait-on: 'http://localhost:19006'
